a = [1,2,3]

try:
    print(a[8])
except Exception as e:
    print(e)
